### PR TITLE
add more attributes and colors

### PR DESCRIPTION
**Pull request by ealmloff**
changes to attributes:
- color
- text_decoration
- font_weight
- font_style
- border_style
- border_color
- border_radius

changes to colors:
- hsl/hsla syntax
- rgb/rgba syntax
- added alpha channel
- added launch configuration for 16 color, 8 bit, or 24 bit rendering

updates tui to 0.17.0

### CODE REVIEW

**Comment by jkelleyrtp** [comment]
Are you happy with this? I'd be happy to merge it :)

**Comment by ealmloff** [comment]
Ok, I'm done now

**Comment by ealmloff** [comment]
Well... I should have checked the tests. All good now

**Comment by jkelleyrtp** [comment]
Awesome!!

**Pull request merged**
