### PR TITLE
html native event handlers

### PR DESCRIPTION
**Pull request by ealmloff**
includes: onmousedown, onmouseup (mouse key is always left due to crossterm limitation), ondrag, onmousemove, onwheel, onresize

### CODE REVIEW

**Comment by jkelleyrtp** [comment]
re: calling listeners on every element...

We definitely need a focus system to narrow down which element to call keydown on. We should also decide what elements participate in focusing and how that nesting works. 

For mouse clicks/hovers/enters/leaves we can probably implement a binary search to figure out which exact element was clicked, thought that's not necessary for this PR.

For the mouseup issue, we can probably assume it's always the last keydown triggered or maybe pop the bottom of a keydown stack off.

When we get a focus system, I think having a dedicated Listener component is still valuable to tap into any/every key event while that component is active.

Overall, very good job! Is this ready to merge or do you still have stuff to change on this branch?

**Comment by ealmloff** [comment]
I'll see if I can fix the mouse and add some more listeners before the merge.

**Comment by ealmloff** [comment]
Ok mouse is done. It now works fine for up to two button presses at once. Ready to merge.

**Comment by jkelleyrtp** [comment]
> Ok mouse is done. It now works fine for up to two button presses at once. Ready to merge.

Over the weekend I was assembling the hover/click detection algorithm in my head and you just implemented exactly. Very good stuff :)

Super happy to merge.

This is amazing! You can seriously build awesome apps with rink now.

**Pull request merged**
